### ISSUE TITLE
Code signing on Mac OSX

### ISSUE THREAD

**Issue by fatihacet** [gokmen/hodext#1]
When I try to open the app it showed me the warning below.

![screenshot](http://f.acet.me/wEIX.png)

Nice project. Very cool name 👍

**Comment by gokmen** [comment]
Thanks! I think I cannot fix that issue without having a proper Apple Developer account and signing the app while release. But for now you can right click and hit Open on the Hodext.app where it will allow you to open it.

**Comment by fatihacet** [comment]
Ok, closing this one then. Thanks 👍
